# coding: utf-8
defaults: &defaults
  app_name: "书愿网"
  upload_url: "http://image-sanvibyfish.b0.upaiyun.com"
  admin_emails: 
    - "admin@admin.com"
    - "test@test.com"
    - "sanvibyfish@gmail.com"
  faye_server: "http://119.147.23.192:4000/faye"
  faye_token: "123456"
development:
  <<: *defaults
  domain:
    host: loclahost
    port: ':3000'

test:
  <<: *defaults

production:
  <<: *defaults
  domain:
    host: bookdate.cn
    port: ''