common: &common
  weibo:
    api_key: "716582019"
    api_secret: "f26bf8bb2b491368b9f64169e69a32c0"
    redirect_uri: "http://www.ibookwish.com/users/auth/weibo/callback"

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common